### PR TITLE
Fix Deprecated function CRM_Core_BAO_Setting::setItem, changed compatibility version

### PR DESCRIPTION
**Pull request by sunilpawar**
Fixed 2 issues.

1. Removed refeernce of Deprecated function
```
User deprecated function: Deprecated function CRM_Core_BAO_Setting::setItem, 
use refer docs for correct methods https://docs.civicrm.org/dev/en/latest/framework/setting/. 
in CRM_Core_Error::deprecatedFunctionWarning() (line 1043 of drupal7/sites/all/modules/civicrm/CRM/Core/Error.php).
```

2. Error on installation

```php
Fatal error: require_once(): Failed opening required 'libphonenumber/PhoneNumberUtil.php' 
(include_path='drupal7/sites/default/files/civicrm/ext/com.cividesk.normalize/:drupal7/si 
in drupal7/sites/default/files/civicrm/ext/com.cividesk.normalize/CRM/Utils/Normalize.php on line 25
```

### CODE REVIEW

**Comment by nganivet** [comment]
Hi @sunilpawar , thanks for the PR. @yashodha , can you please QA and merge? Thanks.

**Comment by sunilpawar** [comment]
> @nganivet sure will do. Thanks!

@yashodha  any chance to merge this ?

**Comment by yashodha** [comment]
@sunilpawar it looks good, Can you please resolve the conflicts and push? Thanks!

**Comment by sunilpawar** [comment]
@yashodha conflicts is resolved..

**Comment by sunilpawar** [comment]
@yashodha conflicts is already resolved. Can you merge it ?

**Pull request merged**
